export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'bg-page': 'rgb(var(--bg-page) / <alpha-value>)',
        'bg-content': 'rgb(var(--bg-content) / <alpha-value>)',
        'bg-wash': 'rgb(var(--bg-wash) / var(--bg-wash-opacity))',
        'text-primary': 'rgb(var(--text-primary) / var(--text-primary-opacity))',
        'text-secondary': 'rgb(var(--text-secondary) / var(--text-secondary-opacity))',
        'text-placeholder': 'rgb(var(--text-placeholder) / var(--text-placeholder-opacity))',
        'border-element': 'rgb(var(--border-element) / var(--border-element-opacity))',
        'border-element-hover': 'rgb(var(--border-element) / var(--border-element-hover-opacity))',
        'border-divider': 'rgb(var(--border-divider) / var(--border-divider-opacity))',
        'interactive-primary': 'rgb(var(--interactive-primary) / <alpha-value>)',
        'interactive-primary-hover': 'rgb(var(--interactive-primary-hover) / <alpha-value>)',
        'interactive-primary-active': 'rgb(var(--interactive-primary-active) / <alpha-value>)',
        'interactive-selected': 'rgb(var(--interactive-selected) / var(--interactive-selected-opacity))',
        'icon-default': 'rgb(var(--icon-default) / var(--icon-default-opacity))',
        'icon-placeholder': 'rgb(var(--text-placeholder) / var(--text-placeholder-opacity))',
        'accent-warm': 'rgb(var(--accent-warm) / <alpha-value>)',
        'accent-success': 'rgb(var(--accent-success) / <alpha-value>)',
        'accent-danger': 'rgb(var(--accent-danger) / <alpha-value>)',
        'gradient-start': 'rgb(var(--gradient-start) / <alpha-value>)',
        'gradient-end': 'rgb(var(--gradient-end) / <alpha-value>)',
      },
      borderRadius: {
        'content': '6px',
        'container': '8px',
        'control': '6px',
      },
      spacing: {
        'fine': '4px',
        'normal': '8px',
        'coarse': '12px',
        'component': '16px',
        'page': '24px',
        'section': '32px',
      },
      fontFamily: {
        'custom': ['Plus Jakarta Sans', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
      },
      fontSize: {
        'header1': ['20px', { lineHeight: '1.3', fontWeight: '700', letterSpacing: '-0.02em' }],
        'header2': ['18px', { lineHeight: '1.4', fontWeight: '700', letterSpacing: '-0.01em' }],
        'header3': ['16px', { lineHeight: '1.5', fontWeight: '600', letterSpacing: '-0.01em' }],
        'value': ['14px', { lineHeight: '1.5', fontWeight: '400', letterSpacing: '-0.005em' }],
        'accent': ['12px', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0em' }],
      },
      boxShadow: {
        'card-sm': '0px 0px 5px 0px rgba(0,0,0,0.1), 0px 0px 1px 0px rgba(0,0,0,0.1)',
        'card-md': '0px 2px 8px 0px rgba(0,0,0,0.1), 0px 1px 1px 0px rgba(0,0,0,0.1)',
        'card-lg': '0px 2px 12px 2px rgba(0,0,0,0.1), 0px 1px 2px 0px rgba(0,0,0,0.1)',
      },
    },
  },
  plugins: [],
};
